apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: phishing-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Rou3/Phishing-App.git
    targetRevision: main
    path: project-files

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

